feat(guides): complete some TODO guides
sapphiredev/website pull request #127
Opened 2022-01-09 13:20 UTC by FC5570

2022-01-09 14:12 UTC, kaname-png commented
Tbh, The guide on how to create an argument needs more context, it lacks information.

2022-01-09 14:13 UTC, FC5570 commented on docs/Guide/additional-information/using-and-extending-container.mdx
> +```
Yes, forgot to do that. I will make changes

2022-01-09 14:13 UTC, FC5570 commented on docs/Guide/arguments/creating-your-own-arguments.mdx
> +Creating an argument can be done by extending the Argument class imported by the framework:
I mean to write, "Creating an argument can be done by extending the Argument class imported from the framework"

2022-01-09 14:18 UTC, megatank58 commented on docs/Guide/arguments/creating-your-own-arguments.mdx
> +Creating an argument can be done by extending the Argument class imported by the framework:
> I mean to write, "Creating an argument can be done by extending the Argument class imported from the framework"

Maybe "Creating an argument can be done by extending the Argument class which can be imported from the framework"

2022-01-09 14:39 UTC, favna requested changes
Please rebase the branch to fix the vercel deploy. Main needed fixing after yesterday's framework PR merge.

2022-01-10 22:42 UTC, favna requested changes
Well done, you nuked your changed by using the app instead of doing it manually.

2022-01-11 03:42 UTC, merged