feat: complete some TODO guides
sapphiredev/website pull request #128
Opened 2022-01-11 07:36 UTC by FC5570

2022-01-11 07:40 UTC, UndiedGamer commented on docs/Guide/arguments/creating-your-own-arguments.mdx
> +Creating an argument can be done by extending the Argument class which can be imported from the framework:
Add an example with Args.make too

2022-01-11 18:41 UTC, favna requested changes

2022-01-11 18:41 UTC, favna commented on docs/Guide/additional-information/accessing-the-client-in-pieces.mdx
>  title: Accessing the `client` in pieces
```suggestion
title: Accessing the client in pieces
```

Doesn't render as inline code anyway

2022-01-11 18:41 UTC, favna commented on docs/Guide/additional-information/using-and-extending-container.mdx
>  title: Using and extending `container`
```suggestion
title: Using and extending container
```

2022-01-11 18:41 UTC, favna commented on docs/Guide/arguments/creating-your-own-arguments.mdx
> +export class TextBasedChannelsArgument extends Argument {
```suggestion
export class TextBasedChannelsArgument extends Argument<TextBasedChannelTypes> {
```

2022-01-11 18:41 UTC, favna commented on docs/Guide/arguments/creating-your-own-arguments.mdx
> +export class ArrayArgument extends Argument {
```suggestion
export class ArrayArgument extends Argument<string> {
```

2022-01-11 18:41 UTC, favna commented on docs/Guide/arguments/creating-your-own-arguments.mdx
> +
```suggestion
:::info

This is essentially the `enum` argument, one of the [Built-in arguments][bia], which was added in version 2.3.0 of @sapphire/framework

:::
```

Add to the bottom of the doc:
```md
[bia]: ../built-in-arguments
```

2022-01-11 18:41 UTC, favna commented on docs/Guide/arguments/creating-your-own-arguments.mdx
> +After that, in your command file:
```suggestion
With all that setup done, you can use the new argument in your command file:
```

2022-01-11 18:43 UTC, favna requested changes

2022-01-11 18:43 UTC, favna commented on docs/Guide/arguments/creating-your-own-arguments.mdx
> +We then augment the @sapphire/framework module to include the new argument in the ArgType interface.
```suggestion
We then augment the `@sapphire/framework` module to include the new argument in the ArgType interface.
```

2022-01-11 18:43 UTC, favna commented on docs/Guide/arguments/creating-your-own-arguments.mdx
> +not, an error is thrown. After that, we augment the @sapphire/framework module to include the new argument in the
```suggestion
not, an error is thrown. After that, we augment the `@sapphire/framework` module to include the new argument in the
```

2022-01-12 20:49 UTC, favna approved these changes

2022-01-12 20:50 UTC, merged