fix: remove `times` when not necessary
sapphiredev/website pull request #143
Opened 2022-02-20 14:02 UTC by HugoFerrant

The option is not used right away but later, so mentioning it here is confusing

2022-02-20 14:23 UTC, favna requested changes
Repeat does have an X amount of times support. Wording of the old text could be better I suppose but we should make mention that it can be X amount of times.

2022-02-20 22:12 UTC, HugoFerrant commented
> Repeat does have an X amount of times support. Wording of the old text could be better I suppose but we should make mention that it can be X amount of times.
You're right. I removed it here because it is optional, but it's worth noticing it.
Maybe we can mention it at the end of the sentence, like "(you can set a limit to the number element parsed with the `times` option which will be covered below)", wdyt @favna  ?

2022-02-21 19:51 UTC, favna commented
Sure, can you make it so @HugoFerrant ?

2022-02-22 22:39 UTC, HugoFerrant commented
> Sure, can you make it so @HugoFerrant ?

@favna  I was doing it, then I remembered this is already a whole codeblock+explanations about this optionnal `times` parameter at the end of the page, with better explanations. So I'm sorry to ask again, but don't you think it's enough ? (last time I ask, if no I'll add the parentheses)

2022-02-23 20:56 UTC, favna approved these changes

2022-02-23 20:58 UTC, merged