fix(guide-il8n): `resolveKey` example
sapphiredev/website pull request #158
Opened 2022-04-11 12:34 UTC by r-priyam

Current example raises -
```ts
Expected 2-3 arguments, but got 1.ts(2554)
[functions.d.ts(33, 185): ]()An argument for 'key' was not provided.
```

Which is because example isn't specifying to resolve key for what, fixed it by specifying `message.guild`.

2022-04-11 19:12 UTC, favna approved these changes

2022-04-12 14:37 UTC, vladfrangu approved these changes

2022-04-12 15:05 UTC, kyranet requested changes
Also fixed the PR's title, `i18n` stands for `internationalization`, which has 18 characters between `i` and `n`.

2022-04-12 15:05 UTC, kyranet commented on docs/Guide/plugins/i18next/getting-started.mdx
> +    await message.channel.send(await resolveKey(message.guild!, 'ping:success'));
You can use message:
```suggestion
    await message.channel.send(await resolveKey(message, 'ping:success'));
```

- https://github.com/sapphiredev/plugins/blob/5c855bd8341f155a41c9b85738541f1f47ac837a/packages/i18next/src/lib/functions.ts#L57-L63
- https://github.com/sapphiredev/plugins/blob/5c855bd8341f155a41c9b85738541f1f47ac837a/packages/i18next/src/lib/functions.ts#L19-L23

2022-04-12 15:10 UTC, kyranet approved these changes

2022-04-12 17:37 UTC, favna approved these changes

2022-04-12 17:37 UTC, merged