feat(docs): add warning about MessageCommand
sapphiredev/website pull request #170
Opened 2022-05-21 07:58 UTC by AnotherBrynAlt

Based on my experience with the manual, and seeing other people in the discord had the issue.

https://discord.com/channels/737141877803057244/737142503043498015/977466262642896896

This change clarifies the need to get Sapphire to load message commands, since by default they will not be. Since message commands are the first example in the guide, it can be confusing.

2022-05-21 10:34 UTC, vladfrangu requested changes

2022-05-21 10:34 UTC, vladfrangu commented on docs/Guide/getting-started/creating-a-basic-command.mdx
> +
```suggestion

Note that by default Sapphire does not load the listeners required for processing message commands. You will need to construct your `SapphireClient` with
the `loadMessageCommandListeners` option set to `true`. See more information about the [client options](https://www.sapphirejs.dev/docs/Documentation/api-framework/interfaces/SapphireClientOptions#loadmessagecommandlisteners).

```

2022-06-01 20:33 UTC, favna requested changes

2022-06-01 20:33 UTC, favna commented on docs/Guide/getting-started/creating-a-basic-command.mdx
> +the `loadMessageCommandListeners` option set to `true`. See more information about the [client options](https://www.sapphirejs.dev/docs/Documentation/api-framework/interfaces/SapphireClientOptions#lo
```suggestion
Note that by default Sapphire does not load the listeners required for processing message commands. You will need to construct your `SapphireClient` with
the `loadMessageCommandListeners` option set to `true`. For more information see the [`SapphireClientOptions#loadMessageCommandListeners`][load-message-ecommands-option] interface.
```

Add to the bottom of this file:

```
[load-message-ecommands-option] ../../Documentation/api-framework/interfaces/SapphireClientOptions#loadmessagecommandlisteners
```

2022-06-01 21:52 UTC, favna commented on docs/Guide/getting-started/creating-a-basic-command.mdx
> +the `loadMessageCommandListeners` option set to `true`. See more information about the [client options](https://www.sapphirejs.dev/docs/Documentation/api-framework/interfaces/SapphireClientOptions#lo
@AnotherBrynAlt You didn't add the link to the bottom of the file as mentioned above

2022-06-01 23:53 UTC, favna approved these changes

2022-06-01 23:54 UTC, favna commented on docs/Guide/getting-started/creating-a-basic-command.mdx
> +../../Documentation/api-framework/interfaces/SapphireClientOptions#loadmessagecommandlisteners
```suggestion
[getting-started]: ./getting-started-with-sapphire
[load-message-commands-option]: ../../Documentation/api-framework/interfaces/SapphireClientOptions#loadmessagecommandlisteners
```

2022-06-01 23:55 UTC, favna approved these changes

2022-06-02 15:56 UTC, merged