feat: utility guides
sapphiredev/website pull request #95
Opened 2021-11-21 13:09 UTC by UndiedGamer

2021-11-22 18:46 UTC, favna requested changes

2021-11-22 18:46 UTC, favna commented on docs/Guide/utilities/Discord Utilities/UsefulRegexes.mdx
> +This regex will match any mention of a channel and return the id of the channel
Add the raw of each regex under each header.

I.e.

---

The raw regex string of this regex is as follows:
```typescript
raw regex here
```

---

No tabs are needed for this. It's the same in everything anyway.

2021-11-22 18:46 UTC, favna commented on docs/Guide/utilities/Discord Utilities/UsefulRegexes.mdx
> +This regex matches any url starting with http/https
```suggestion
This regex matches any url starting with `http` or `https`
```

2021-11-22 18:46 UTC, favna commented on docs/Guide/utilities/Discord Utilities/UsefulRegexes.mdx
> +Regex that can capture any animated or non-animated custom Discord emoji. Similar to FormattedCustomEmoji and unlike
When referencing different regexes, make those links.

2021-11-22 18:46 UTC, favna commented on docs/Guide/utilities/Discord Utilities/UsefulRegexes.mdx
> +This regex matches any animated or non-animated custom Discord emoji \*without the wrapping `<...>` symbols. This means
Wild `\*`?

2021-11-22 18:46 UTC, favna commented on docs/Guide/utilities/DiscordJS Utilities/PaginatedMessage.mdx
> +;
```suggestion
```

2021-11-22 18:46 UTC, favna commented on docs/Guide/utilities/DiscordJS Utilities/PaginatedMessage.mdx
> +import Tabs from '@theme/Tabs';
```suggestion
---

import Tabs from '@theme/Tabs';
```

Remember, page headers are automatic.

2021-11-22 18:46 UTC, favna commented on docs/Guide/utilities/fetch.mdx
> +import TabItem from '@theme/TabItem';
Move to the top

2021-11-22 18:46 UTC, favna commented on docs/Guide/utilities/Discord Utilities/UsefulRegexes.mdx
> +Sapphire provides a lot of Regexes that you can use in your code
Add install of @sapphire/discord-utilities

2021-11-22 18:46 UTC, favna commented on docs/Guide/utilities/stopwatch.mdx
> +Provides a set of methods and properties that you can use to accurately measure elapsed time.
This can be a bit more descriptive. I know, I know, you copied it over. That's bad on us too.

2021-11-23 01:29 UTC, UndiedGamer commented on docs/Guide/utilities/Discord Utilities/UsefulRegexes.mdx
> +Regex that can capture any animated or non-animated custom Discord emoji. Similar to FormattedCustomEmoji and unlike
Sure

2021-11-23 01:30 UTC, UndiedGamer commented on docs/Guide/utilities/Discord Utilities/UsefulRegexes.mdx
> +This regex matches any animated or non-animated custom Discord emoji \*without the wrapping `<...>` symbols. This means
Wild copy pasta

2021-11-30 21:42 UTC, favna requested changes
#97 has been merged and this PR has been rebased. Please migrate your `<Tabs` for JS/ESM/TS to the next plugin based syntax

2021-12-16 09:54 UTC, UndiedGamer commented
## TODO for now

- [ ]  Add raw regex for reference
- [ ]  Update guides for snowflake

i will re-request a review once i am done with this

2021-12-16 10:11 UTC, UndiedGamer commented
@kyranet can you please review the snowflake.mdx file? because you were the one who reworked the package

2021-12-16 10:25 UTC, kyranet requested changes

2021-12-16 10:25 UTC, kyranet commented on docs/Guide/utilities/snowflake.mdx
> +// Generate a snowflake with the given epoch const uniqueId = snowflake.generate();
```suggestion
// Define a custom epoch
const epoch = new Date('2000-01-01T00:00:00.000Z');

// Create an instance of Snowflake
const snowflake = new Snowflake(epoch);

// Generate a snowflake with the given epoch
const uniqueId = snowflake.generate();
```

2021-12-16 10:25 UTC, kyranet commented on docs/Guide/utilities/snowflake.mdx
> +Deconstructing snowflakes is the same for every snowflake
Should probably explicitly mention `DiscordSnowflake` and `TwitterSnowflake` so they're made aware that they don't have to build a Snowflake instance, but that they can use those 2 exports.

2021-12-25 08:06 UTC, favna requested changes
no spaces in paths allowed 

![image](https://user-images.githubusercontent.com/4019718/147380521-cbec469f-893e-423a-b538-f8756e9dd5f3.png)


Use underscores and then if you want it to show up as `Discord Utilities` on the sidebar add a `category.yml`

2021-12-25 21:45 UTC, favna requested changes

2021-12-25 21:45 UTC, favna commented on docs/Guide/utilities/Discord_Utilities/UsefulRegexes.mdx
> +:::
```suggestion
:::note

If you don't know what a Regex is check the
[Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)

:::
```

2022-01-08 12:58 UTC, favna approved these changes

2022-01-08 12:58 UTC, merged